# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
RAND_NAME_SUFFIX = Socket.gethostname

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.provider "virtualbox" do |v|
   v.memory = 2048
end  

  config.vm.define 'centos6-vm' do |machine|
    machine.vm.box = "centos6-vm"
	machine.vm.box_url = '~/docs/vm/vbox/centos65.box', "http://www.lyricalsoftware.com/downloads/centos65.box"
	machine.vm.hostname = "centos6-vm-#{RAND_NAME_SUFFIX}"
  end

  config.ssh.forward_agent = true
end
