#vim :set ts=4 sw=4 sts=4 et :
developers_groups:
 - 'developres'
 - 'ninjas'

ops_groups:
 - 'ops'
 - 'wheel'

robots_groups:
 - 'robots'
 - 'terminators'

company_groups:
 - 'company'
 - 'company555'

all_groups: "{{developers_groups + ops_groups + robots_groups + company_groups}}"

users_accounts:
 - name: 'gkomissarov'
   uid: 4000
   gecos: "Gregory Komissarov"
   homedirectory: '/home/gkomissarov'
   email: 'gregory.komissarov@novardis.com'
   shell: '/bin/bash'
   groups: "{{ ','.join(company_groups + ops_groups) }}"
   authorized_keys: [
   'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzamDL0Vv2T0Oq/wXyuPBmoWWOOycAKF+cD0x+4dU4LPxxj9fDjOCHgkncrv3vHUGtevChL45g0la4Ex0hpiTrhW42+eRCP37fm4Ykh9F3dvN9C8PjD2MHc/BpXR1hCMI2L+rqLLeJIZ4Q99SVw6yud23HjL35c/JfSEgfeqx+mCcwnSCDdCYSNsZqNU/fCB7IE4mmyKVRUxMTYFMXCZuTS0mV3eIbsu4Hw+lsyCYyYdbqv9fOAOTSJMPRz1mJrjMtWXkhyWVwohd7JoWFJN2zHLoPm//7F/zW3hU7GwgguSs5/afGqyfJsrID2zoEpOqX7K02/YwACk29CJL4n5WR gkomissarov@valhalla'
   ]
 - name: 'robot'
   uid: 2001
   disabled: False
   gecos: "VCS\ robot"
   homedirectory: "/home/robot"
   email: 'robot@company.com'
   groups: "{{ ','.join(company_groups + robots_groups) }}"
   authorized_keys: [
   'ssh-rsa XXX'
   ]
